const numero = Number(prompt('Digite um número'));
const numeroPromt = document.getElementById('numero');
const texto = document.getElementById('texto');
numeroPromt.innerHTML = numero;
texto.innerHTML += `<p>Raiz quadrada ${numero ** 0.5}`
texto.innerHTML += `<p>${numero} é inteiro: ${Number.isInteger(numero)}</p>`
texto.innerHTML += `<p>É NaN ${Number.isNaN(numero)}</p>`
texto.innerHTML += `<p>Arredondando para baixo: ${Math.floor(numero)}</p>`
texto.innerHTML += `<p>Arredondando para cima: ${Math.ceil(numero)}</p>`
texto.innerHTML += `<p>Com duas casa decimais: ${numero.toFixed(2)}</p>`